!ExperimentConfig
    batch_size: 128
    checkpoint_dir: null
    data_dir: null
    exp_root: !Path
        data: /home/psychopath/exp
    experiment_name: DIFFRWKV
    from_pretrained: null
    metrics_to_log: !list [loss, perplexity]
    metrics_to_save_cp: !list [loss, perplexity]
    mlflow_continue_run: true
    mlflow_enabled: true
    mlflow_http_timeout: 600
    mlflow_log_to_remote_freq: 120
    mlflow_run_id: null
    mlflow_run_name: null
    mlflow_server: https://united-namely-macaw.ngrok-free.app
    number_of_workers: 1
    out_dir: null
    pin_memory: true
    seed: null
    split_val_ratio: 0.2
    tensorboard: null
    use_tensorboard: false
    val_batch_size: 32
    work_dir: null
