!TokenizerConfig
    add_prefix_space: false
    continuing_subword_prefix: null
    dropout: null
    end_of_word_suffix: null
    lowercase: false
    merges: null
    min_frequency: 2
    special_tokens: !list [<|endoftext|>, <|padding|>]
    trim_offsets: true
    unicode_normalizer: "nfkc"
    vocab: null
    vocab_size: 50254
