!TrainerConfig
    accelerator: auto
    accumulate_grad_batches: 1
    check_val_every_n_epoch: 1
    default_root_dir: null
    deterministic: null
    devices: auto
    enable_checkpointing: null
    enable_model_summary: null
    enable_progress_bar: null
    gradient_clip_algorithm: null
    gradient_clip_val: null
    inference_mode: true
    log_every_n_steps: null
    max_steps: -1
    num_nodes: 1
    num_sanity_val_steps: null
    precision: 32-true
    val_check_interval: null
